name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      continue-on-error: true
      run: |
        chmod +x ./gradlew
        ./gradlew build
